### ISSUE TITLE
Set up a way to version the tiles

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-processing#7]
- [ ] do some research on versioning vector tiles - how do other people do it?
- [ ] identify if any of the options we have is sensible (mbtiles in artifactory? or in gitlab? or?)

**Comment by lindsayplatt** [comment]
Similar to https://github.com/usgs-makerspace/wbeep-viz/issues/40, this seems moot now that we are moving to a "poor-man's" versioning via GitHub. 

Disagree? Please reopen and comment!

Including @mwernimont so he gets this notification.
